In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


Bad key "text.kerning_factor" on line 4 in
/opt/miniconda3/envs/ironhack_env/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.2/matplotlibrc.template
or from the matplotlib source distribution


In [2]:
data = pd.read_csv('../data/diamonds_train.csv')
data.head()

carat        cut color clarity  depth  table  price     x     y     z
0   1.21    Premium     J     VS2   62.4   58.0   4268  6.83  6.79  4.25
1   0.32  Very Good     H     VS2   63.0   57.0    505  4.35  4.38  2.75
2   0.71       Fair     G     VS1   65.5   55.0   2686  5.62  5.53  3.65
3   0.41       Good     D     SI1   63.8   56.0    738  4.68  4.72  3.00
4   1.02      Ideal     G     SI1   60.5   59.0   4882  6.55  6.51  3.95

In [3]:
data.describe(include='all')

carat    cut  color clarity         depth         table  \
count   40455.000000  40455  40455   40455  40455.000000  40455.000000   
unique           NaN      5      7       8           NaN           NaN   
top              NaN  Ideal      G     SI1           NaN           NaN   
freq             NaN  16220   8455    9749           NaN           NaN   
mean        0.797706    NaN    NaN     NaN     61.752841     57.446133   
std         0.475544    NaN    NaN     NaN      1.431725      2.233535   
min         0.200000    NaN    NaN     NaN     43.000000     43.000000   
25%         0.400000    NaN    NaN     NaN     61.000000     56.000000   
50%         0.700000    NaN    NaN     NaN     61.800000     57.000000   
75%         1.040000    NaN    NaN     NaN     62.500000     59.000000   
max         4.500000    NaN    NaN     NaN     79.000000     95.000000   

               price             x             y             z  
count   40455.000000  40455.000000  40455.000000  40455.000000  
unique           NaN           NaN           NaN           NaN  
top              NaN           NaN           NaN           NaN  
freq             NaN           NaN           NaN           NaN  
mean     3928.444469      5.729392      5.732819      3.537154  
std      3992.416147      1.124453      1.146650      0.697062  
min       326.000000      0.000000      0.000000      0.000000  
25%       945.000000      4.710000      4.720000      2.910000  
50%      2397.000000      5.690000      5.710000      3.520000  
75%      5331.000000      6.540000      6.540000      4.035000  
max     18823.000000     10.230000     58.900000      8.060000

In [22]:
data['carat'].unique()

array([1.21, 0.32, 0.71, 0.41, 1.02, 1.52, 1.01, 0.31, 1.14, 0.44, 0.93,
       1.51, 1.65, 1.5 , 0.43, 0.38, 0.85, 1.53, 1.54, 0.3 , 1.3 , 1.  ,
       0.9 , 1.55, 1.16, 0.35, 0.97, 1.19, 0.7 , 0.8 , 2.  , 0.5 , 0.51,
       1.04, 0.64, 0.78, 0.52, 0.33, 0.47, 1.59, 0.34, 0.74, 1.08, 0.79,
       1.33, 0.58, 1.22, 1.62, 0.55, 1.64, 1.1 , 1.03, 0.56, 1.13, 0.91,
       1.24, 2.3 , 0.27, 0.36, 1.77, 1.06, 1.27, 0.92, 2.01, 1.83, 0.23,
       0.77, 2.07, 1.11, 1.56, 0.96, 2.25, 1.18, 1.72, 0.59, 0.57, 0.72,
       0.4 , 0.42, 1.36, 1.15, 0.54, 1.86, 1.41, 0.75, 2.22, 1.23, 0.88,
       1.25, 0.28, 1.82, 1.37, 1.2 , 1.05, 0.39, 0.6 , 0.76, 0.25, 0.73,
       0.53, 0.63, 2.53, 0.65, 0.62, 1.4 , 1.7 , 0.83, 1.17, 0.46, 1.26,
       1.58, 2.13, 0.24, 1.07, 2.04, 0.45, 1.09, 2.05, 1.31, 0.29, 0.84,
       1.12, 0.81, 2.75, 0.22, 0.66, 1.74, 1.57, 1.29, 1.69, 0.49, 2.24,
       2.02, 0.61, 1.32, 1.87, 0.37, 0.67, 1.73, 0.82, 1.46, 1.71, 0.26,
       2.64, 2.14, 2.33, 2.03, 1.35, 2.57, 1.39, 1.

In [31]:
data['cut'].unique()

array(['Premium', 'Very Good', 'Fair', 'Good', 'Ideal'], dtype=object)

In [14]:
data['color'].unique()

array(['J', 'H', 'G', 'D', 'F', 'E', 'I'], dtype=object)

In [15]:
data['clarity'].unique()

array(['VS2', 'VS1', 'SI1', 'SI2', 'IF', 'VVS1', 'VVS2', 'I1'],
      dtype=object)

In [17]:
data['depth'].unique()

array([62.4, 63. , 65.5, 63.8, 60.5, 61.2, 65.2, 62.3, 61.8, 61.7, 58. ,
       60.1, 61.6, 57.5, 62.1, 60.8, 61.9, 60.7, 61. , 62. , 61.3, 62.9,
       63.2, 61.1, 62.5, 60.4, 60.2, 63.5, 60.3, 62.2, 55.2, 59.8, 62.6,
       63.4, 63.9, 63.7, 61.5, 59.6, 63.3, 64.8, 62.7, 58.8, 59.7, 62.8,
       65.3, 57.8, 59.4, 58.7, 61.4, 64.3, 64.6, 60.9, 63.6, 57.4, 63.1,
       60. , 60.6, 58.9, 56.6, 58.6, 59.1, 59.5, 59.2, 43. , 57.6, 59.3,
       64.1, 58.5, 59.9, 70.6, 64.7, 59. , 70.1, 64.5, 64. , 57.9, 58.1,
       65.1, 66.7, 64.2, 58.4, 57.7, 64.4, 66. , 70.5, 58.2, 55. , 65. ,
       67. , 56.5, 58.3, 65.8, 65.4, 69.8, 64.9, 57.3, 55.8, 65.6, 56.7,
       68.6, 66.5, 65.7, 68.3, 66.2, 66.1, 71.6, 66.4, 56.2, 68. , 67.7,
       67.8, 56.9, 56.1, 70.2, 44. , 67.6, 56.8, 67.3, 66.3, 66.8, 67.4,
       66.9, 68.7, 56.3, 67.9, 65.9, 56.4, 68.2, 54.6, 57. , 57.2, 67.2,
       70.8, 55.6, 53.4, 56. , 54.2, 54. , 66.6, 57.1, 67.5, 68.9, 67.1,
       55.5, 69.6, 55.3, 68.8, 72.2, 53.3, 69.7, 55

In [18]:
data['table'].unique()

array([58. , 57. , 55. , 56. , 59. , 54.2, 63. , 61. , 60. , 54. , 53.9,
       64. , 55.6, 56.4, 51. , 62. , 53. , 54.1, 65. , 55.5, 54.6, 54.4,
       61.5, 52. , 53.5, 53.7, 56.1, 56.3, 66. , 54.7, 55.9, 53.8, 53.4,
       60.7, 56.2, 54.8, 59.9, 55.7, 55.4, 56.6, 61.4, 62.4, 43. , 59.1,
       57.6, 57.7, 56.7, 58.4, 59.8, 53.1, 58.3, 55.8, 55.2, 56.9, 55.3,
       67. , 57.2, 57.4, 57.5, 59.5, 60.8, 57.8, 54.5, 53.3, 54.3, 54.9,
       60.3, 58.2, 56.5, 58.8, 60.5, 53.6, 60.9, 61.9, 58.5, 55.1, 73. ,
       70. , 57.1, 59.4, 60.6, 60.2, 56.8, 69. , 59.6, 68. , 59.7, 62.5,
       58.1, 62.3, 58.6, 59.2, 57.3, 50. , 76. , 52.4, 60.1, 64.2, 62.8,
       59.3, 49. , 62.2, 57.9, 44. , 95. , 53.2, 79. , 58.9, 60.4, 61.8,
       63.3, 62.6, 61.2, 61.7, 58.7, 52.8, 50.1, 61.3, 63.4, 64.3, 63.5])

In [19]:
data['price'].unique()

array([ 4268,   505,  2686, ...,  6570, 10070, 12615])

In [40]:
cut = data['cut'].value_counts()
cut

Ideal        16220
Premium      10260
Very Good     9095
Good          3663
Fair          1217
Name: cut, dtype: int64

In [41]:
color = data['color'].value_counts()
color

G    8455
E    7325
F    7177
H    6277
D    5049
I    4032
J    2140
Name: color, dtype: int64

In [42]:
clarity = data['clarity'].value_counts()
clarity

SI1     9749
VS2     9248
SI2     6929
VS1     6066
VVS2    3799
VVS1    2774
IF      1327
I1       563
Name: clarity, dtype: int64

In [8]:
mean_price = data.pivot_table(index=['color'],aggfunc='mean')
mean_price

carat      depth        price      table         x         y  \
color                                                                    
D      0.653036  61.721886  3134.943157  57.344959  5.404704  5.409541   
E      0.658835  61.659836  3088.342526  57.494567  5.413894  5.418651   
F      0.731503  61.689954  3677.355720  57.409726  5.601393  5.607254   
G      0.774382  61.752785  4023.214902  57.287889  5.684102  5.687183   
H      0.910355  61.827481  4476.469014  57.533503  5.981431  5.984082   
I      1.026791  61.873214  5090.868800  57.562574  6.216099  6.215675   
J      1.166500  61.909626  5346.234112  57.790701  6.527285  6.525570   

              z  
color            
D      3.336782  
E      3.338709  
F      3.455930  
G      3.508856  
H      3.693629  
I      3.842078  
J      4.039879

In [46]:
min_price = data.pivot_table(index=['color'],aggfunc='min')
min_price

carat clarity   cut  depth  price  table     x     y     z
color                                                            
D       0.20      I1  Fair   54.2    357   52.0  3.77  3.72  2.29
E       0.20      I1  Fair   53.3    326   44.0  3.79  3.75  2.06
F       0.22      I1  Fair   52.3    342   50.0  0.00  0.00  0.00
G       0.23      I1  Fair   43.0    354   52.0  0.00  0.00  0.00
H       0.23      I1  Fair   52.7    337   50.0  0.00  0.00  0.00
I       0.23      I1  Fair   55.3    334   43.0  3.94  3.90  0.00
J       0.23      I1  Fair   43.0    335   52.0  3.93  3.90  2.46

In [49]:
max_price = data.pivot_table(index=['color'],aggfunc='max')
max_price

carat clarity        cut  depth  price  table      x      y     z
color                                                                   
D       3.40    VVS2  Very Good   71.6  18693   73.0   9.42   9.34  6.27
E       3.05    VVS2  Very Good   79.0  18731   73.0   9.26   9.25  5.66
F       3.01    VVS2  Very Good   71.0  18791   95.0   9.24   9.13  5.73
G       3.01    VVS2  Very Good   72.9  18818   76.0   9.44   9.37  6.16
H       4.13    VVS2  Very Good   71.8  18795   73.0  10.00  58.90  8.06
I       4.01    VVS2  Very Good   71.3  18823   70.0  10.14  10.10  6.31
J       4.50    VVS2  Very Good   73.6  18710   68.0  10.23  10.16  6.72

In [84]:
pivot1 = data.pivot_table(values='price',
                          columns='cut',
                          index='carat',
                          aggfunc='sum')
pivot1

cut       Fair     Good    Ideal  Premium  Very Good
carat                                               
0.20       NaN      NaN    734.0   1446.0        NaN
0.21       NaN      NaN      NaN   3036.0      386.0
0.22     337.0      NaN      NaN   1620.0        NaN
0.23     369.0  11530.0  15852.0  10105.0    66418.0
0.24       NaN   4531.0  27962.0   6356.0    54905.0
...        ...      ...      ...      ...        ...
3.51       NaN      NaN      NaN  18701.0        NaN
4.00       NaN      NaN      NaN      NaN    15984.0
4.01       NaN      NaN      NaN  30446.0        NaN
4.13   17329.0      NaN      NaN      NaN        NaN
4.50   18531.0      NaN      NaN      NaN        NaN

[270 rows x 5 columns]

In [83]:
pivot2 = data.pivot_table(values='price',
                          columns='clarity',
                          index='carat',
                          aggfunc='sum')
pivot2

clarity       I1      IF     SI1    SI2      VS1      VS2     VVS1     VVS2
carat                                                                      
0.20         NaN     NaN     NaN  345.0      NaN   1835.0      NaN      NaN
0.21         NaN     NaN   326.0  394.0      NaN   2702.0      NaN      NaN
0.22         NaN     NaN   812.0    NaN      NaN   1145.0      NaN      NaN
0.23         NaN  2948.0   739.0  775.0  11814.0   9310.0  27254.0  51434.0
0.24         NaN  5830.0  2195.0    NaN  11986.0   8505.0  30335.0  34903.0
...          ...     ...     ...    ...      ...      ...      ...      ...
3.51         NaN     NaN     NaN    NaN      NaN  18701.0      NaN      NaN
4.00     15984.0     NaN     NaN    NaN      NaN      NaN      NaN      NaN
4.01     30446.0     NaN     NaN    NaN      NaN      NaN      NaN      NaN
4.13     17329.0     NaN     NaN    NaN      NaN      NaN      NaN      NaN
4.50     18531.0     NaN     NaN    NaN      NaN      NaN      NaN      NaN

[270 rows x 8 columns]

In [89]:
pivot3 = data.pivot_table(values='price',
                          columns='color',
                          index='carat',
                          aggfunc='sum')
pivot3

color        D        E        F       G        H        I        J
carat                                                              
0.20     734.0   1446.0      NaN     NaN      NaN      NaN      NaN
0.21    1544.0   1878.0      NaN     NaN      NaN      NaN      NaN
0.22     404.0    741.0    812.0     NaN      NaN      NaN      NaN
0.23   16663.0  46237.0  26422.0  9156.0   5042.0    414.0    340.0
0.24   10930.0  31791.0  33807.0  8374.0   6636.0   1784.0    432.0
...        ...      ...      ...     ...      ...      ...      ...
3.51       NaN      NaN      NaN     NaN      NaN      NaN  18701.0
4.00       NaN      NaN      NaN     NaN      NaN  15984.0      NaN
4.01       NaN      NaN      NaN     NaN      NaN  15223.0  15223.0
4.13       NaN      NaN      NaN     NaN  17329.0      NaN      NaN
4.50       NaN      NaN      NaN     NaN      NaN      NaN  18531.0

[270 rows x 7 columns]

In [12]:
#standart deviation
data.std()

carat       0.475544
depth       1.431725
table       2.233535
price    3992.416147
x           1.124453
y           1.146650
z           0.697062
dtype: float64

In [13]:
data.median()

carat       0.70
depth      61.80
table      57.00
price    2397.00
x           5.69
y           5.71
z           3.52
dtype: float64

In [14]:
data.quantile(.25)

carat      0.40
depth     61.00
table     56.00
price    945.00
x          4.71
y          4.72
z          2.91
Name: 0.25, dtype: float64

In [15]:
data.quantile(.75)

carat       1.040
depth      62.500
table      59.000
price    5331.000
x           6.540
y           6.540
z           4.035
Name: 0.75, dtype: float64